### ISSUE TITLE
Are you available for freelancing?

### ISSUE THREAD

**Issue by seekingdeep** [wuzuowuyou/paint_xml#1]
@wuzuowuyou hi,
i have seen some of your work in text detection, it was interesting.
i have some work dealing with Text-Detection.
Are you available for freelancing? if so, then can i contact you and share more information

**Comment by wuzuowuyou** [comment]
Contact me by email
837007389@qq.com

**Comment by seekingdeep** [comment]
have a look at the email that i sent you

**Comment by seekingdeep** [comment]
@wuzuowuyou i sent you an email, you still didn't reply
